name: CI

on:
  push:
  pull_request:

jobs:
  nix:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          persist-credentials: false

      - name: Install Nix
        uses: cachix/install-nix-action@v26
        with:
          nix_path: nixpkgs=channel:nixos-unstable

      - name: Show flake
        run: nix flake show

      - name: Formatter check
        run: nix fmt -- --check

      - name: Lint (statix)
        run: nix develop -c statix check

      - name: Deadnix
        run: nix develop -c deadnix --fail .

      - name: Build NixOS hosts
        run: |
          nix build .#nixosConfigurations.home-hp.config.system.build.toplevel -L
          nix build .#nixosConfigurations.home-dell.config.system.build.toplevel -L
